task: CIFAR100
synthesizer: Pattern


batch_size: 64
test_batch_size: 100
lr: 0.1
momentum: 0.9
decay: 0.0005
epochs: 223
poison_epoch: 123
poison_epoch_stop: 223
save_on_epochs: [] # [30, 50, 80, 100, 120, 150, 170, 200]
optimizer: SGD
log_interval: 100

poisoning_proportion: 0.5
backdoor_label: 8

resume_model: resume_model/model_cifar100_pretrain_epoch_122.pt.tar

save_model: False #False
log: True

transform_train: True

fl: True
fl_no_models: 20
fl_local_epochs: 2
fl_poison_epochs: 15
fl_total_participants: 20
fl_eta: 1
fl_sample_dirichlet: True
fl_dirichlet_alpha: 0.9

fl_number_of_adversaries: 4
fl_weight_scale: 5
fl_adv_group_size: 5
# fl_single_epoch_attack: 200

attack: 'DataFreeAttack'
defense: 'EqLen' # 'EqLen'  'FLAME' 'FedAvg'  'RFLBAT'  'Foolsgold'
fl_num_neurons: 50
noise_mask_alpha: 0 # 0.5
lagrange_step: 0.1