task: GTSRB
synthesizer: Pattern


batch_size: 64
test_batch_size: 100
lr: 0.01
momentum: 0.9
decay: 0.0005
epochs:  100
poison_epoch: 1
poison_epoch_stop: 100
save_on_epochs: [] 
optimizer: SGD
log_interval: 100

poisoning_proportion: 0.5
backdoor_label: 8

resume_model: resume_model/gtsrb_model

save_model: False #False
log: True

transform_train: True

fl: True
fl_no_models: 20
fl_local_epochs: 2
fl_poison_epochs: 15
fl_total_participants: 20
fl_eta: 1
fl_sample_dirichlet: False
fl_dirichlet_alpha: 0.9

fl_number_of_adversaries: 4
fl_weight_scale: 1
fl_adv_group_size: 5
# fl_single_epoch_attack: 200

attack: 'DataFreeAttack' # 'ThrDFed' 'ModelReplace' 'DataFreeAttack' 'DataFreeNoise'
defense: 'FedAvg' #
fl_num_neurons: 5
noise_mask_alpha: 0 # 0.5
lagrange_step: 0.1